### ISSUE TITLE
Adding new payment processors

### ISSUE THREAD

**Issue by AshRaghav** [4teamwork/ftw.shop#66]
Hi,

I am quite new to Plone and struggling with adding a new external Payment processor. Is there a good documentation that I can refer to and complete the setup?

Thanks

**Comment by AshRaghav** [comment]
@lukasgraf - Hi, have noticed that you have been actively involved with this product development previously. Will you be able to help me with this please?

Thanks

**Comment by lukasgraf** [comment]
Hey @AshRaghav - unfortunately it's been several years since I actively worked on this package. I would also need to get a local development environment going, and read up again on all the concepts in order to provide you with any help. And I'm currently swamped in client work so that I unfortunately don't have the time for that at this point.

The other thing is - as you noticed, customizing payment processors unfortunately isn't documented, and even if it was, it's being done in a way that isn't friendly at all for Plone newcomers, sorry. Please don't take this the wrong way, but I don't think I'm able to help you with this.
